### ISSUE TITLE
Feature toggle correct value not reflecting right away after context Update

### ISSUE THREAD

**Issue by coderscode2** [Unleash/unleash-proxy-client-js#152]
### Describe the bug

I have a feature toggle `xyz` and its value is true for userId 123. 

Right after user logs in successfully, we update the context with userId. The `xyz` toggle value is still coming back as `false` even after userId update in the context. This is causing issues.

**Comment by coderscode2** [comment]
@thomasheartman Can you please let me know if and when you have any update on this issue?

**Comment by megancooper** [comment]
Also experiencing this issue, but wanted to give more insight: I noticed that it seems like the `update` event is consistently being emitted, but will occasionally fail to invoke the client's update callback

**Comment by megancooper** [comment]
For others experiencing this issue and using react, I found a workaround in the meantime by swapping the `useFlag` hook for directly accessing the flag value from the `FlagsContext`:

```diff
import {useFlag, FlagContext} from '@unleash/proxy-client-react';

-const myFlag = useFlag('flag-name');
+const {isEnabled} = useContext(FlagContext);
+const showGiftCards = isEnabled('flag-name');
```

The issue seems to be that the `update` event, which seems to be consistently emitting when its supposed to, sometimes fails to actually invoke [the callback that the react library is using in the `useFlag` hook](https://github.com/Unleash/proxy-client-react/blob/main/src/useFlag.ts#L27)

**Comment by daveleek** [comment]
Hello @coderscode2! One question that came up as we were looking at this: are you awaiting the update of the context? It's an async method that communicates with the server, so it needs to be awaited

**Comment by coderscode2** [comment]
@daveleek Yes, I am using await but it still returns incorrect value
