### ISSUE TITLE
How do I init using instanceId?

### ISSUE THREAD

**Issue by edrichhans** [Unleash/unleash-proxy-client-js#23]
The other SDKs (Node, Go, etc) all seem to have a way to initialize using instance ID. Is this possible here as well? Trying out the feature flag implementation of Gitlab but I'm having trouble setting it up

**Comment by ivarconr** [comment]
Hi @edrichhans, it does not make much sense for this SDK to use an instanceId because it connects via the Unleash Proxy, which again connects to the unleash-api. If you need an instance id to be passed to Unleash API you would need to configure that in the proxy. 

https://docs.getunleash.io/sdks/unleash-proxy/
