### ISSUE TITLE
instanceId in metrics

### ISSUE THREAD

**Issue by jameswnl** [Unleash/unleash-proxy-client-js#86]
### Describe the feature request

Hi, the [instanceId](https://github.com/Unleash/unleash-proxy-client-js/blob/f66fcc0a181745533184a1eb1696d9fa66a1257f/src/metrics.ts) currently is always set to `browser`.

What is the plan for this field? Can we have the `context` being stored there? So that usage metrics can be even more useful

### Solution suggestions

How about store something meaningful in the `instanceId` e.g. user `sessionID`, or user email etc

**Comment by FredrikOseberg** [comment]
@jameswnl

Hi. I don't think there has been much thought behind this. Our metrics data format was largely dictated by the NodeJS implementation, and was included here because the contract demanded it. I do like the idea of making the usage metrics more useful, though maybe that should be an expansion of the contract rather than using the instanceId field to store this data. 

Another important consideration is our privacy focus. We do not want to receive sensitive user / domain settings. If we just dump the entire context into metrics, then suddenly we will capture potentially sensitive data that belongs in your application. We are of course, always open to discussing how we can improve unleash, and improving metrics is an area of interest for us - but it will require some thought on the implementation that does not compromise our core values.

**Comment by FredrikOseberg** [comment]
As an added note, if you want more analytics related data, you might want to take a look at [impression data](https://docs.getunleash.io/advanced/impression-data). This will allow you to capture usage and exposure in your own application.
